# Generated by Django 2.0.5 on 2018-12-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a task description.', max_length=80)),
                ('start_date', models.DateField(blank=True, help_text='Enter start date', max_length=100, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Enter end date', max_length=100, null=True)),
                ('repeat', models.CharField(blank=True, help_text='Choose if it repeats.', max_length=80, null=True)),
                ('times', models.BigIntegerField(blank=True, help_text='Choose how many times it repeats', max_length=1000, null=True)),
            ],
        ),
    ]
