# Generated by Django 2.1.1 on 2018-11-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a task description.', max_length=80)),
                ('startDate', models.DateField(help_text='Enter start date', max_length=100)),
                ('endDate', models.DateField(help_text='Enter end date', max_length=100)),
                ('repeat', models.CharField(help_text='Choose if it repeats.', max_length=80)),
                ('times', models.BigIntegerField(help_text='Choose how many times it repeats', max_length=1000)),
            ],
        ),
    ]
